name: Sync GitHub to GitLab

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest # Use a fresh Ubuntu environment for the job

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4 # Action to checkout your GitHub repository code

      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add GitLab Remote and Push
        run: |
          GITLAB_REMOTE_URL="https://sync_token:${{ secrets.GITLAB_PAT }}@${{ secrets.GITLAB_REPO_URL#https:// }}"
          
          git remote add gitlab "$GITLAB_REMOTE_URL" || git remote set-url gitlab "$GITLAB_REMOTE_URL"

          echo "Pushing to GitLab repository..."
          git push --mirror gitlab
          echo "Synchronization complete!"
        env:
          GITLAB_PAT: ${{ secrets.GITLAB_PAT }}
          GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}